# Generated by Django 4.1 on 2022-08-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='frens',
            field=models.ManyToManyField(through='main_app.Fren', to='main_app.profile'),
        ),
    ]
