# Generated by Django 4.1 on 2022-08-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_fren_super_fren_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fren',
            name='super_fren_status',
            field=models.BooleanField(default=False),
        ),
    ]
