# Generated by Django 4.1 on 2022-08-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_fren_super_fren_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fren',
            name='name',
            field=models.ManyToManyField(to='main_app.profile'),
        ),
    ]
