# Generated by Django 4.1 on 2022-09-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_fren_super_fren_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fren',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='fren',
            field=models.ManyToManyField(to='main_app.fren'),
        ),
        migrations.AlterField(
            model_name='fren',
            name='super_fren_status',
            field=models.BooleanField(default=True, verbose_name='Are you two super frens?!'),
        ),
    ]
