# Generated by Django 4.1 on 2022-09-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_fren_name_profile_fren_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fren',
            name='most_favorite_color',
            field=models.CharField(default='Xanadu??', max_length=24),
        ),
    ]
