# Generated by Django 4.1 on 2022-09-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_fren_most_favorite_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fren',
            name='super_fren_status',
            field=models.BooleanField(verbose_name='Are you two super frens?!'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='upload',
            field=models.ImageField(upload_to='main_app/static/images/'),
        ),
    ]
